# .github/workflows/deploy.yml
name: Deploy to Oracle VPS

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync files to VPS
        run: |
          rsync -avz --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            ./ ubuntu@149.130.181.250:/home/ubuntu/horarios_app_backend

      - name: Install dependencies and restart app
        run: |
          ssh ubuntu@149.130.181.250 << 'EOF'
            cd /home/ubuntu/horarios_app_backend
            npm install --production
            pm2 startOrRestart ecosystem.config.js
          EOF
